name: Deploy 404 Page

on:
  workflow_call:
    inputs:
      token:
        required: true
        type: secret

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ inputs.token }}
          folder: src/404
          branch: gh-pages
          clean: 'true'
