name: CI Develop

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: |
          npm run build --- --base-href develop

      - name: Deploy Build
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist/pisa-pizza
          branch: gh-pages
          target-folder: develop
          clean: 'false'

      - name: Deploy 404.html
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: src/404
          branch: gh-pages
          clean: 'false'
